### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by ghost** [Nightbringer21/fridump#2]
When i try to run fridump, i got an error that says:

```
P:\Programming\fridump-master>python fridump.py
  File "fridump.py", line 44
    print logo
             ^
SyntaxError: Missing parentheses in call to 'print'
```

I'm not a python programming expert so i'm not sure why it couldn't print the logo. I'm using Python 3.6.0 on Windows, PIP and Frida are installed. Path environment variable are correctly set

**Comment by anantshri** [comment]
code is written in python 2 syntax use python 2 to execute it and it will work.

**Comment by andruwik777** [comment]
@anantshri , but how can we use fridump with python 2 if frida works only with python 3?

**Comment by DummybugStudios** [comment]
I know I'm a little late but frida _is_ available for python2

**Comment by Nightbringer21** [comment]
Frida is available both for python2 and python3. I have just pushed an update that is supporting both versions. Let me know if there are any further issues.
