### ISSUE TITLE
app name has two spaces. Error when trying to run it.

### ISSUE THREAD

**Issue by poldenais** [Nightbringer21/fridump#31]
Hi, 

if an app name has two spaces in it does it matter. Like "App Test Name"?

I'm getting fridump: error: unrecognized arguments: Test Name”

it's like it doesn't like the second space?

I've tried \ in the spaces also.

**Comment by poldenais** [comment]
Got it working now leaving out the double quotes and putting in \ as the spaces and then finishing in terminal with ; as it popped to a new Line.

**Comment by Cyber-m0nk** [comment]
hi @poldenais how did you solve this? This is how you are using command right fridump.py -U -s "App\Test\Name;" ?
