### ISSUE TITLE
Can't connect to App. Have you connected the device?

### ISSUE THREAD

**Issue by YNWho-0** [Nightbringer21/fridump#32]
Hello, so i get this error when running this command,
`C:\Users\User\Desktop\fridump>fridump.py -U -s "APP Name"`

        ______    _     _
        |  ___|  (_)   | |
        | |_ _ __ _  __| |_   _ _ __ ___  _ __
        |  _| '__| |/ _` | | | | '_ ` _ \| '_ \
        | | | |  | | (_| | |_| | | | | | | |_) |
        \_| |_|  |_|\__,_|\__,_|_| |_| |_| .__/
                                         | |
                                         |_|
`Can't connect to App. Have you connected the device?`
And yes i have installed the frida server.
`C:\Users\User\Desktop\fridump>frida-ps -U
Waiting for USB device to appear...
  PID  Name
-----  -----------------------------------------------
12096  APP Name
12133  Cydia
12159  Mail
12148  Messenger

**Comment by YNWho-0** [comment]
Apparently it doesnt work on any app.

**Comment by Nightbringer21** [comment]
Hi, can you provide me with a few more information to try and identify the issue?
Some things that would be useful:
* Frida version
* Frida tools version
* Running the tool in debug mode and providing the output

**Comment by YNWho-0** [comment]
I actually got a fix to it.
When i searched on the issues i saw someone that said it was fixed because he went from windows to macbook.
And i know windows doesn’t really support ios phones and i know that itunes and icloud makes the connection better so i installed thoses then restarted my pc and then it worked! Also frida-ps worked instantly when i used it after.

**Comment by Nightbringer21** [comment]
Hmmm, that's definitely a weird issue. I might need to try and replicate it to my Mac as I don;t think I have encountered it before. Still, it is weird that frida-ps was working even if slower and fridump was not (as it is purely calling frida and nothing else).
Closing the issue as resolved and might re-visit it when I have a bit more time.

**Comment by danangtriatmaja-infosec** [comment]
hmmm
