### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by pandasauce** [Nightbringer21/fridump#4]
Hi @Nightbringer21 

I noticed that this repository does not contain a license, and is therefore considered ["All rights reserved" by default](http://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github). As such, from legal standpoint, currently nobody can base their code on this project and contributing is a grey area.

Would you consider adding a license to resolve this?

You can easily pick one at https://tldrlegal.com/

Thanks

**Comment by oxr463** [comment]
@Nightbringer21 why was this closed without adding a license to the repository?
