### ISSUE TITLE
Incomplete strings

### ISSUE THREAD

**Issue by OnkarSagare27** [Nightbringer21/fridump#43]
Is there any way to look for a specific string cuz it splits out the strings and dumps into different files, I want the whole string....

**Comment by hongsolo9** [comment]
You get a strings.txt in the output directory if you have "-s" as one of the options.
`python3 fridump.py -U -v -o app_out_directory -s "someapp"`

**Comment by OnkarSagare27** [comment]
Yeah, I know that, but I'm trying to find a specific string, but when the dumper dumps the string I'm looking for, it gets split up into small parts and I find them at random locations.
