### ISSUE TITLE
Memory access violation

### ISSUE THREAD

**Issue by andruwik777** [Nightbringer21/fridump#7]
During dumping memory from Android device by USB I see a lot of 

> Starting Memory dump...
> Oops, memory access violation!-------------------------------] 2.23% Complete
> Oops, memory access violation!-------------------------------] 2.84% Complete
> Oops, memory access violation!-------------------------------] 3.65% Complete
>...

Is it OK?
For me it would be better to give user more friendly message because this confuses me every time I see this.. Or even document this somehow in the readme file ))

**Comment by sparklingAngel0706** [comment]
i am getting the same issue . Please look into this issue
