### ISSUE TITLE
Hi, it seem on iOS 9 was not work

### ISSUE THREAD

**Issue by masbog** [Nightbringer21/fridump#8]
Hi, i try to attach the program, but fridump always said "Can't connect to App. Have you connected the device?"

$ frida-ps -U -> ok, i can get all PID and process name

how to fix it?

**Comment by sparklingAngel0706** [comment]
I am getting the same issue when using android rooted moto e running cynogenmod and os level marshmallow

**Comment by priyankn** [comment]
For future ppl:
It should work . I had the same issue, make sure you are passing in the the exact process name from 'frida-ps; output. 

Alternatively try passing in the -s (for string parameter) as well.

**Comment by masbog** [comment]
now it work with the latest of frida server... no issue again... now my issue on iOS 10.2 iPhone 7 where jailbreak with Meridan.... :(

**Comment by poldenais** [comment]
hi does this work with iOS 11.3.1 with Electra JB?

**Comment by poldenais** [comment]
I can get it working on one app but for the app I'm testing im getting "Can't connect to App. Have you connected the device?"

**Comment by Nightbringer21** [comment]
Hi poldenais,

I am closing this issue, as if it is working with one app, then it seems to be a direct issue with the app you are trying to test. I would suggest checking if the name provided is correct or if there is a space in the  name, which would need to be within quotes to work
